version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "5005:5005"  # Debug port
    volumes:
      - ./src:/app/src  # Mount source code for hot reload
      - ./target:/app/target  # Mount target directory
      - ~/.m2:/root/.m2  # Mount Maven cache
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=passw0rd
      - MYSQL_DB=tp_obj2_db
      - SPRING_DEVTOOLS_REMOTE_SECRET=mysecret
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=passw0rd
      - MYSQL_DATABASE=tp_obj2_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 